# Project information
site_name: 'WordLynx - human-readable geocoding'
site_author: 'Cait Harrigan'
site_url: 'https://harrig12.github.io/WordLynx/'

# Repository
repo_name: 'harrig12/WordLynx'
repo_url: 'https://github.com/harrig12/WordLynx'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Teal'
    accent: 'Teal'
  font: 
    text: 'Montserrat'
  logo: 
    icon: 'map'
  favicon: 'img/map.png'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/harrig12'


# Navigation
nav:
    - Home: index.md
    - Take me to the web app: https://hcvdb.med.ubc.ca/useful-links/wlns/
    - Canadian Open Data Competition Submission: pages/openData.md
    - About WordLynx: pages/about.md
    - Introductory Slides: img/introductionSlides.pdf
    - WordLynx Poster: img/WordLynx-poster.pdf

# Search
extra:
  search:
    language: 'en'

# Extensions
markdown_extensions:

  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    