# Project information
site_name: 'WordLynx - human-readable geocoding'
site_author: 'Cait Harrigan'
site_url: 'https://harrig12.github.io/WordLynx/'

# Repository
repo_name: 'harrig12/WordLynx'
repo_url: 'https://github.com/harrig12/WordLynx'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Teel'
    accent: 'Brown'
  font: 'Baloo Chettan'
  logo: 
    icon: 'map'
  favicon: 'img/map.png'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/harrig12'


# Navigation
nav:
    - About: index.md
    - Canadian Open Data Competition: pages/openData.md
    - More:
      - WordLynx Manuscript: pages/content.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
    